
select * from used_cars;

#1--what is the revenue generated by different companies?

select company,sum(price) from used_cars
group by company;


#2--Which car models have the highest average selling price?

select model, avg(price)
from used_cars
group by model;

#3--What is the average car price by fuel type?

select fueltype, avg(price)
from used_cars
group by fueltype;

#4--Which cities have the highest average used car prices?

select * from used_cars;

select city,avg(price)
from used_cars
group by city
order by avg(price) desc;

#5--What is the price distribution across different manufacturing years?

select * from used_cars;

select modelyear,min(price),avg(price),max(price),sum(price)
from used_cars
group by modelyear
order by modelyear;


#6--Which brands retain the highest resale value?

select * from used_cars;

select company,round(avg(price),2) as resale_value
from used_cars
group by company
order by resale_value desc;

#7--How does kilometers driven affect car price?

select 
	case
		when kilometer <2000 then '0-2k'
        when kilometer <10000 then '2k-10k'
        when kilometer <20000 then '10k-20k'
        when kilometer <60000 then '20k-60k'
        when kilometer <100000 then '60k-100k'
        when kilometer <200000 then '100k-200k'
        else '200k+'
	end as recorded_range,
round(avg(price),2) avgprice
from used_cars
group by recorded_range
order by avgprice desc;


#8--Which car age range gives the best value for money?

select * from used_cars;

select owner ,round(avg(price),2) as avg_price
from used_cars
group by owner
order by avg_price;


select current_user()

